const knjige = [
    {"id": "1", "naziv": "Mundo Libre", "pisac": "Marko Krstic", "zanr": "Novi naslovi", "slika": "img/mundoLibre.jpg", 
    "opis": "Ne ostavljamo deci samo kuću i novac. Ostavljamo im državu u kojoj treba da žive. Od dobitnika Ćopićeve nagrade stiže nam intimna i dosad neispričana priča o poslednjim danima legendarnog revolucionara Ernesta Če Gevare. „Savremeni imperijalizam je ponizio Čea na sebi svojstven način, uklopio ga je u sopstveni sistem i obesmislio ono za šta se borio. Marko Krstić je svojim romanom dao doprinos, vredan svake hvale, jednom novom pogledu na čoveka za koga su mnogi čuli a sve manje je onih koji o njemu išta znaju.“ Vladimir Kecmanović"},
    {"id": "2", "naziv": "Drugi Ajnštajn", "pisac": "Mari Benedikt", "zanr": "Novi naslovi", "slika": "img/drugiAjnstajn.jpg", 
    "opis": "„Divna, tužna i nezaboravna priča o briljantnoj Milevi Ajnštajn, ženi koja je ostala u senci velikana.“ Sju Monk Kid, autorka bestselera Tajni život pčela Mileva Marić je fascinantna i briljantna fizičarka. Ona je drugi Ajnštajn. Mileva Marić je oduvek bila drugačija i razlikovala se od ostalih devojaka. Većina dvadesetogodišnjakinja već je u brakovima, a ne studiraju fiziku na elitnom ciriškom univerzitetu koji posećuju samo muški studenti i svi pokušavaju da je zasene veštim proračunima. A onda njen kolega Albert Ajnštajn počinje da se zanima za nju i Milevin svet se okreće naglavačke. Njihova veza se pretvara u partnerstvo kako srca tako i uma, ali u njihovom braku neće biti mesta za više od jednog genija."},
    {"id": "3", "naziv": "Manastir", "pisac": "Milomir Đukanović", "zanr": "Novi naslovi", "slika": "img/manastir.jpg", 
    "opis": "Devedesetih godina prošlog veka Anastas Jovanović, ratni fotograf strane novinske agencije, istovremeno traga za zarobljenim bratom na hrvatskom ratištu i mladalačkom ljubavlju koju nije preboleo. Da bi dobio neophodne informacije, mora da pretraži Beograd uzduž i popreko, pa je prinuđen da se susreće da domaćim i stranim kriminalcima, agentima obaveštanijh službi, korumpiranim policajcima, pokvarenim političarima... Sve dok iznenada u jednoj novobeogradskoj kafani ne sazna za mračnu tajnu nastalu davno pri izgradnji Narodne skupštine. On ne sluti da će razotkrivanje te tajne rešiti sudbine svih junaka ovog romana. Roman Manastir predstavlja izuzetno i autentično književno delo u kojem se pisac neprekidno poigrava sa pričom i njenom formom, meša književne žanrove, ukršta ironiju i grotesku, i žestoko kritikuje društvo. "},
    {"id": "4", "naziv": "Ubisvet", "pisac": "Siniša Soćanin", "zanr": "Novi naslovi", "slika": "img/ubisvet.jpg", 
    "opis": "Zašto profesionalac likvidira nevine ljude? Neko ubija obične građane, ljude bez ikakve veze s kriminalom. Inspektorka Sofija preuzima slučaj, uprkos tome što se još nije oporavila od samoubistva svog supruga. Njoj pomaže mladi inspektor Petar, ali oni su nemoćni jer nema nikakvih tragova. Riđokosa je teoretičarka zavere čiji je brat jedna od žrtava u nizu nerazjašnjenih ubistava. U magnovenju, ona pokreće sopstvenu istragu. Usput upoznaje Bezimenog, ćutljivog muškarca sa amnezijom koji ima neobičnu sposobnost empatije: on sve vreme oseća ono što osećaju ljudi oko njega, čak i ako ti drugi svoja osećanja potiskuju ili pokušavaju da prikriju. Riđokosa odlučuje da ga upotrebi u istrazi jer bi joj svojom sposobnošću pomogao da prepozna ubicu među onima koje sumnjiči."},
    {"id": "5", "naziv": "Imenik klasične starine", "pisac": "Vladeta Janković", "zanr": "Novi naslovi", "slika": "img/imenikKlasicne.jpg", 
    "opis": "Od autora Mitova i legendi i Antičkih izreka. Leksikon poput Imenika klasične starine nikada ne može izgubiti na svežini jer su njegovi junaci i njihove priče utkani u istoriju svetske kulturne i umetničke baštine, a može se reći – i u naš svakodnevni život. Ovaj imenik se, po uvodnim rečima sastavljača, profesora Vladete Jankovića, od sličnih danas dostupnih leksikona kod nas i u svetu razlikuje po tome što, „pored mitoloških, obuhvata i stvarne ličnosti od važnosti za društvenu i kulturnu istoriju, a donekle i po tome što nastoji da, u okvirima pojedinih odrednica, ukaže na značaj ove ili one mitološke ili istorijske figure u potonjem umetničkom i uopšte duhovnom stvaralaštvu. Zbog toga mitološke odrednice uglavnom sadrže osnovnu verziju legende, njeno simboličko značenje i najpoznatije obrade u književnosti, likovnoj umetnosti i muzici.“ Pri tome se, kad god se pružila prilika, u ovom imeniku ukazuje i na vezu našeg tla i tradicije sa klasičnom starinom, pre svega helenskim i starorimskim nasleđem, što predstavlja njegov poseban značaj i bogatstvo."},
    {"id": "6", "naziv": "Brit-Mari je bila tu", "pisac": "Fredrik Bakman", "zanr": "Novi naslovi", "slika": "img/britMari.jpg", 
    "opis": "Od autora bestselera Čovek po imenu Uve i Moja baka vam se izvinjava. Zabavna, dirljiva i zanosna priča o ljubavi i novim prilikama, ali i o neočekivanim prijateljstvima koja nas mogu naučiti tome ko smo zaista i šta smo sve u stanju da uradimo. Brit-Mari ne može da podnese nered. Ona uvek večera u isto vreme i započinje svoj dan u šest ujutru, jer se samo ludaci bude kasnije. I nije pasivno-agresivna. To nipošto. Mada ljudi ponekad tumače njene dobronamerne predloge kao kritiku. U šezdeset trećoj godini svega joj je dosta. Najzad napušta svoj četrdesetogodišnji brak lišen ljubavi i pronalazi posao na jedinom mestu gde je to moguće: u Varoši, oronulom naselju razorenom ekonomskom krizom. Za sitničavu Brit-Mari, navikavanje na taj novi svet sa bučnom decom, blatnjavim podovima i cimerom koji je (doslovno) pacov neće ići nimalo lako."},
    {"id": "7", "naziv": "U senci masline", "pisac": "Lusinda Rajli", "zanr": "Novi naslovi", "slika": "img/uSenciMasline.jpg", 
    "opis": "Autorka bestseler serijala Sedam sestara. Čudesna kuća. Nezaboravno leto. Postoji izreka koja kaže da svako ko prvi put dođe u Pandoru mora da se zaljubi... Prošlo je dvadeset četiri godine otkad je Helena provela magičan raspust na Kipru, gde se prvi put zaljubila. Kad joj kum u nasledstvo ostavi Pandoru, sad oronulu kuću, ona se vraća na Kipar, u mesto koje je nekad volela, da provede leto sa porodicom. Pandora i krajolik oko nje idilični su kao i pre, i Heleni naviru brojna sećanja. Ipak, neka od njih ona ne želi da podeli sa mužem Vilijamom i sinom Aleksom, trinaestogodišnjakom suočenim sa promenama koje donosi odrastanje dok očajnički želi da sazna istinu o svom pravom ocu..."},
    {"id": "8", "naziv": "Teodorin prsten", "pisac": "Vanja Bulić", "zanr": "Novi naslovi", "slika": "img/teodorinPrsten.jpg", 
    "opis": "Pripremajući se za modnu reviju na kojoj će manekenke nositi i srednjovekovni srpski nakit, novinar Novak Ivanović odlazi u manastir Banjsku i obilazi ruševine rudarskog grada Novo Brdo... Tamo nazire deo strašne tajne i stare legende o prstenu vizantijske princeze i potom srpske kraljice Teodore, majke cara Dušana Silnog: umreće brzo svako ko ga stavi na ruku! Još 1915. godine, razbivši u kosovskom manastiru Banjskoj sarkofag kraljice Teodore, prsten je uzeo, tačnije – ukrao, regent Aleksandar Karađorđević i odneo ga u Beograd. Sto godina kasnije prsten se pojavio na ruci lepe manekenke na reviji upriličenoj u čast modnog magnata iz Milana. Pozajmljen za tu priliku iz Narodnog muzeja u Beogradu, prsten je istovremeno i opsesija tajnog društva iz Italije zakletog u nameri da obnovi istočno rimsko carstvo, pa agent tajnog društva takođe dolazi na reviju kojoj prisustvuje beogradski džet-set, ambasadori, policajci, obaveštajci, političari, tajkuni, mafijaši, novinari..."},
    {"id": "9", "naziv": "Ženski razgovori", "pisac": "Dušan Radović", "zanr": "Top Lista", "slika": "img/zenskiRazgovori.jpg", 
    "opis": "Ljubav se ne sme terati i izbijati iz žene – jer to je žena! To je ono glavno u ženi, onaj njen glavni životni sok! Muškarci mogu biti kakvi hoće i ne treba za to da brinu! Žene će ih voleti, bez obzira...! Žensko srce stalno gori i svako ko mu priđe može se ogrejati! Zbirka duhovitih priča iz ugla različitih žena (i muškaraca) o ljubavi, sreći i zajedničkom življenju. Posmatrajući muški svet iz ženske perspektive u dramskim crticama, Radović kroz humor ali i gorčinu analizira ono što svakodnevno živimo. Ironična ali dobrodušna, knjiga u kojoj će se svako pronaći."},
    {"id": "10", "naziv": "Devojka koja je čitala u metrou", "pisac": "Kristin Fere-Fleri", "zanr": "Top Lista", "slika": "img/devojka.jpg", 
    "opis": "U duhu Čudesne sudbine Amelije Pulen i Čekaj me na poslednjoj stranici – moderna bajka o mladoj ženi čiji će se život preokrenuti kad se pridruži igri Knjige bez granica. Žilijet putuje metroom svakog dana u isto vreme. Najviše voli da oko sebe posmatra ljude koji čitaju. Stariju gospođu sa zbirkom recepata, bibliofila – ljubitelja retkih izdanja, devojku koja uvek plače na strani 247... Jednog dana Žilijet odlučuje da izađe dve stanice ranije i krene nepoznatom ulicom do posla. Pogled joj privlače visoka zarđala metalna vrata, koja su odškrinuta. Na vratima piše velikim plavim slovima: Knjige bez granica. A iza tih vrata dočekaće je usamljeni knjižar koji očekuje svog kurira. Posao njegovih kurira nije samo razmena knjiga. Oni moraju da prepoznaju narednog čitaoca, da naslute kome je baš ta knjiga potrebna. Zaintrigirana, Žilijet se pridružuje igri, a njen život, nekada dosadan i monoton, biće ispunjen neobičnim avanturama."},
    {"id": "11", "naziv": "Jedna nit", "pisac": "Trejsi Ševalije", "zanr": "Top Lista", "slika": "img/jednaNit.jpg", 
    "opis": "Autorka svetskog bestselera Devojka sa bisernom minđušom. Dirljiva priča o ženi koja u predvečerje Drugog svetskog rata dolazi u grad sa nadom da će se izboriti za svoje pravo na sreću. Godina 1932. Pošto joj je Veliki rat odneo i voljenog brata i verenika, Vajolet Spidvel postaje „prekobrojna žena“, pripadnica naraštaja osuđenog na usedelički život jer je u ratu izginulo mnogo mladića. Ipak, ona ne može da se pomiri sa tim da će joj ceo život biti sveden na brigu o ožalošćenoj i ogorčenoj majci."},
    {"id": "12", "naziv": "Jedna od Nas", "pisac": "Osne Sejerštad", "zanr": "Top Lista", "slika": "img/cetiriKise.jpg", 
    "opis": "Priča o masakru u Norveškoj. Autorka bestselera „Knjižar iz Kabula“. „Jedna od nas je knjiga o pripadnosti i zajednici, ali i o tome šta se događa kada ne možemo da je pronađemo. Ovo je i priča o Norveškoj. Savremena priča o svima nama.“ Andeš Bering Brejvik je 22. jula 2011. godine detonirao bombu ispred kancelarije norveškog premijera u centru Osla i pritom ubio osmoro ljudi. Zatim je otišao u kamp za omladinu na šumovitom ostrvu Uteja gde je ubio još šezdeset devetoro ljudi. Većina njih su bili mladi članovi Radničke partije. Osne Sejerštad analizira taj dan, Brejvikovo preobraćenje od nadarenog deteta iz bogatog dela grada u masovnog ubicu i posledice ovog događaja koji je zauvek promenio jednu miroljubivu i prosperitetnu zemlju."},
    {"id": "13", "naziv": "Voleti nekog poput tebe", "pisac": "Havijer Bosk", "zanr": "Top Lista", "slika": "img/voletiNekog.jpg", 
    "opis": "Himna ljubavi i sećanju, ali i iskrena počast knjigama i knjižarama. Žan-Pjer Zanardi je slobodan duh i galerista na šetalištu na levoj obali Sene. Paulina Oms vodi spokojan porodičan život u Barseloni. Sudbina je htela da Paulina dođe u Pariz na svadbu svoje rođake i sretne Žan-Pjera. Neočekivana privlačnost između njih zauvek će im promeniti život. Ne samo da Žan-Pjer liči na Marčela Mastrojanija i ima neobičan hobi da traži literaturu o leptirima u najlepšim knjižarama na svetu, već je majstor da svaki običan trenutak pretvori u neobično, nadahnjujuće iskustvo."},
    {"id": "14", "naziv": "Upitnik je pola srca", "pisac": "Sofija Lundberj", "zanr": "Top Lista", "slika": "img/upitnikJePolaSrca.jpg", 
    "opis": "Autorka bestselera Crveni adresar. Upitnik je pola srca je priča o prevazilaženju stida i krivice, o istini i prihvatanju svoje prirode, ali pre svega o tome kako da volimo. Elin Bouls vodi savršen život. Ona je uspešna fotografkinja u Njujorku, udata je za divnog Sema i zajedno imaju sedamnaestogodišnju ćerku Alis. Ali njihovoj savršenoj porodičnoj slici uvek je nešto nedostajalo. Jednog dana Elin dobija pismo od Fredrika, školskog druga i jedinog iskrenog prijatelja iz siromašnog detinjstva provedenog na ostrvu Gotland nadomak Švedske. On je glas iz prošlosti koji je Elin svim snagama nastojala da zaboravi i sakrije od svih, čak i od najbližih. Neočekivana vest budi različita sećanja i razmišljanja. Nastaje razdor između Elin i njene porodice, a nju obuzima stid zbog onoga što je nekada učinila, i progoni je tajna zbog koje je pobegla sa ostrva gde se nikad nije vratila."},
    {"id": "15", "naziv": "Unutrašnjost", "pisac": "Tea Obreht", "zanr": "Top Lista", "slika": "img/unutrasnjost.jpg", 
    "opis": "Autorka svetskog bestselera Tigrova žena i dobitnica nagrade Orindž. „I sam Gabrijel Garsija Markes pozavideo bi na ovako veštom prepletu realizma sa fantastičnim momentima. Bićete očarani ovim romanom.“ Kirkus Reviews U bezakonitim, sušom ispijenim krajevima Arizone 1893. naporedo teku dva jedinstvena života. Nora je nepokolebljiva žena koja živi u pustinji i čeka povratak muža, koji je otišao da potraži vodu za svoje ožednelo domaćinstvo, i starijih sinova, koji su iščezli nakon burne svađe. Uz nju je samo njen najmlađi sin, koji je ubeđen da oko njihove kuće vreba tajanstvena zver. Luri je bivši odmetnik i čovek kog proganjaju duhovi. On viđa duše koje uvek nešto žele od njega, a on pribežište od njihovih čežnji nalazi u nesvakidašnjoj ekspediciji na Divlji zapad. Način na koji će se Lurijeva putanja, prkoseći smrti, ukrstiti s putanjom Norinih nedaća najveće je iznenađenje i najnapetiji sloj ovog izvanrednog romana."},
    {"id": "16", "naziv": "Nestvarno a stvarno", "pisac": "Živojin Petrović", "zanr": "Top Lista", "slika": "img/nestvarnoAStvarno.jpg", 
    "opis": "Neverovatne priče iz naše prošlosti Da li ste čuli za prvog Srbina na Severnom polu? Ili za prvog Srbina koji je u stomaku nosio blizance? Znate li ko su bili jahači torpeda? Znate li da je jedan Srbin bio najbolji iluzionista na svetu? Koji je to brod potonuo od stida? Priče iz naše prošlosti – herojske, duhovite, zapanjujuće ili bizarne – često mogu da nas iznenade i zaprepaste. Živojin Petrović je strastveni sakupljač takvih crtica, a marljivim istraživanjem dokopao se očaravajućih podataka i preneo nam ih ne bi li se spasile iz čeljusti zaborava. Bilo da je reč o anegdotama, beleškama ili filmskim avanturama, svako poglavlje ove knjige upozorava da je pamćenje središnji deo naše kulture."},
    {"id": "17", "naziv": "Priče o rečima", "pisac": "Vuk Stefanović Karadžić", "zanr": "Akcioni", "slika": "img/priceORecima.jpg", 
    "opis": "Male priče iz Vukovog Rječnika i Srpskih narodnih poslovica. Pojedine reči koje je uneo u svoja izdanja rečnika srpskog jezika, kao i poslovice i zagonetke koje je zapisivao i objavljivao, Vuk nije tumačio uobičajenim leksikografskim definicijama, nego uglavnom ilustrovao i odgonetao pravim malim proznim medaljonima, kratkim i zaokruženim „kažama“ sačuvanim u narodu. Na taj način ostavio nam je niz priča o rečima i izrazima (babini kozlići, vještica, grebenište, dembel, đavolak, zloguk, kuka i motika, mora, pričešalo, raskovnik, tamni vilajet, uprđeti, džaba i mnoge druge), koje se s punim pravom mogu smatrati kako dopunom narodnog blaga objedinjenog u njegovim narodnim pripovetkama, tako i još jednim dokazom Vukovog pripovedačkog dara."},
    {"id": "18", "naziv": "Idiot - I tom", "pisac": "Fjodor Mihailovič Dostojevski", "zanr": "Akcioni", "slika": "img/idiot.jpg", 
    "opis": "„Najhrabriji roman Fjodora Dostojevskog.“ Džozef Frank Je li istina, kneže, da ste jednom govorili da će svet spasti „lepota“? Gospodo – obratio se glasno svima – knez tvrdi da će lepota spasti svet. Nakon nekoliko godina provedenih u švajcarskom sanatorijumu, knez Lav Nikolajevič Miškin vraća se u Petrograd. Polako se ponovo uključuje u visoko društvo, kojim vladaju novac, moć i romantične intrige. Dobronameran i naivan, knez Miškin će se naći u ljubavnom trouglu sa mladom i lepom Aglajom Jepančinom i zloglasnom Nastasjom Filipovnom. Međutim, njegov čisto estetski doživljaj ženske lepote bez ikakve primese seksualnih želja u velikoj meri uzrokovaće drame u njihovim odnosima. U suprotnosti sa ostatkom sveta, njegova bezazlenost i gotovo detinja iskrenost od Miškina će načiniti najpozitivnijeg ali i najneprilagođenijeg junaka Fjodora Dostojevskog. "},
    {"id": "19", "naziv": "Obećao si mi", "pisac": "Mirjana Bobić", "zanr": "Akcioni", "slika": "img/obecaoSiMi.jpg", 
    "opis": "i druge pesme „Poezija je upravo dokaz života. Ako vaš život dobro gori, onda je poezija – pepeo.“ Leonard Koen „Poezija je siroče tišine. Reči nikada ne mogu biti jednake iskustvu koje stoji iza njih.“ Čarls Simić „Čitam poeziju da bih sačuvala vreme.“ Merilin Monro „Naježila sam se. Ne znam kako i zašto. Nije mi bilo hladno. Je l' prošao neki duh? Ne, to je bila poezija.“ Silvija Plat"},
    {"id": "20", "naziv": "Svaštara", "pisac": "Dušan Radović", "zanr": "Akcioni", "slika": "img/svastara.jpg", 
    "opis": "ŠTA SAM TO RADIO? Probijao sam led da bih mogao disati. Borio se protiv tuđe i svoje dosade. Pokušavao da se setim nečeg drugog. Izmišljao imena sopstvenim iskustvima i saznanjima. Igrao se, jer raditi ne volim. Bežao iz svog malog i siromašnog života. Udvarao se drugima. Grickao, bockao, kraduckao i živuckao. Hteo sam da budem bolji pisac, ali nisam umeo. Uz niz bisera kratke forme i osvrta Dušana Radovića na svoj život i stvaralaštvo, sada imamo i retku priliku da vidimo tekstove onako kako su izašli iz pisaće mašine, njegove početne ideje, crtežiće, privatne fotografije, nepoznate radove... Pošto prvi put donosi sadržaj razglednica i pisama koje je Dušan slao svom sinu Milošu, zbirka Svaštara prikazuje velikog pisca i u ulozi izvanrednog oca. Ukratko, u ovoj knjizi nalazi se sve ono bez čega bi portret Dušana Radovića bio nepotpun."},
    {"id": "21", "naziv": "Zvona starog Tokija", "pisac": "Ana Šerman", "zanr": "Akcioni", "slika": "img/zvonaStarogTokija.jpg", 
    "opis": "Upoznajte Tokio i njegove građane Kad su šoguni vladali Japanom, dan je imao dvanaest časova. Svaki je nosio ime po jednoj životinji kineskog zodijaka, tako da je u zoru bio čas zeca, a u suton čas pevca. Podne je bilo čas konja, čas tigra padao je baš pred izlazak sunca, kad se polazi na putovanja i kad se ljubavnici rastaju. U Edu su se časovi menjali s godišnjim dobima: čas zimskog dana bio je znatno kraći nego čas letnjeg dana. Noćni čas je bio dug zimi, kratak leti. Od 1632. do 1854. godine vladari Japana strogo su ograničavali dodir sa stranim zemljama, nametnuvši Japancima gotovo potpunu izolaciju u kojoj je odnegovana upečatljiva i jedinstvena kultura. Opčinjavajućom prozom s mnogo čulnih detalja Ana Šerman prikazuje potragu za velikim zvonima koji su u doba šoguna stanovnicima Eda, današnjeg Tokija, govorila koliko je sati. Istraživanje Tokija postaje meditacija ne samo o vremenu nego i o istoriji, sećanju i nepostojanosti."},
    {"id": "22", "naziv": "Zašto spavamo", "pisac": "Metju Voker", "zanr": "Akcioni", "slika": "img/zastoSpavamo.jpg", 
    "opis": "Razotkrivanje moći spavanja i sanjanja. „Knjiga koju treba držati pored kreveta, iz najpraktičnijih razloga“ New York Times Zadivljujuće istraživanje svrhe i moći spavanja iz pera direktora Centra za proučavanje spavanja na Univerzitetu Berkli. Autor razjašnjava zašto je spavanje jedan od najvažnijih vidova našeg života, ujedno i onaj koji najmanje razumemo. Sve donedavno nauka nije imala odgovor na pitanja zašto spavamo i čemu spavanje služi ili otkud takve pogubne posledice po zdravlje kad nam je san uskraćen. U poređenju s nagonima za hranom, pićem i razmnožavanjem – razumevanje svrhe spavanja je mnogo teže i zahtevnije. U samom mozgu spavanje obogaćuje razne funkcije, uključujući našu sposobnost za učenje, pamćenje i donošenje logičkih odluka. Ono podešava naše emocije, obnavlja imunološki sistem, fino usklađuje rad našeg metabolizma i reguliše apetit. Sanjarenje stvara prostor virtuelne realnosti u kojem mozak spaja prošlo i sadašnje znanje, čime nadahnjuje našu kreativnost."},
    {"id": "23", "naziv": "Biblija", "pisac": "Nenad Racković", "zanr": "Akcioni", "slika": "img/biblija.jpg", 
    "opis": "„Novi zavet beogradskog antihrista!“ Marko Vidojković „Pred čitaocima je zablistalo jevanđenje po psihijatru Nenada Rackovića, sročeno u vidu beleški, brižljivo vođenih tokom sedamdeset devet dana lečenja. Jedini Rackovićev apostol marljivo je hvatao njegove rastrzane misli, pretvarajući ih u psihotične psalme o ljubavnim lavirintima, apstinentskim krizama, recidivskim iskušenjima, te hroničnoj izgubljenosti u godinama kada je smrt sve bliža, a današnjica košmar bez buđenja. U Petom godišnjem dobu Racković je beležio poslednje otkucaje srca Beograda, dok nas u Bibliji suočava sa svežim lešom nekada svog i nekada našeg grada. Nenad Racković je nadživeo univerzum kojim je vladao, a prostora za stvaranje novog nema. Zato beži u snove, pa nas tako u Bibliji čeka i trinaest vrućih noći, koje predstavljaju Rackovićev poslednji rezervat neograničene slobode.“ Marko Vidojković"},
    {"id": "24", "naziv": "Prodavnica Tajni", "pisac": "Dino Bucati", "zanr": "Akcioni", "slika": "img/prodavnicaTajni.jpg", 
    "opis": "Integralno izdanje prvi put na srpskom jeziku! Uplašeni stanari zgrade provode besane noći zbog kapljice vode koja se penje uz stepenice umesto da se sliva, jedna majka umalo što nije izazvala svetski rat zbog šarenog jajeta, vanzemaljci se spuštaju na krov crkve da bi im sveštenik protumačio značenje krsta, a meštani jednog sela užasavaju se pitomog psa lutalice… Prodavnicu tajni Bucati je priredio dve godine pre smrti, u nadi da će upoznati ljude s najboljim što je napisao. U ovim pripovetkama nekad vizionarskim, nekad grotesknim, lirskim i realističnim ili bajkolikim, gde se fantastično i začudno smenjuju sa humorom i ironijom, Bucati ukazuje na ono bizarno koje se krije iza banalnog, na tajne koje okružuju savremenog čoveka – osvetljavajući tako košmarnu stranu naše svakidašnjice."},
    {"id": "25", "naziv": "Neispričane priče", "pisac": "Rajko Grlić", "zanr": "Akcioni", "slika": "img/neispricane.jpg", 
    "opis": "„Čitav život sakrivao sam se iza filmskih junaka. Živio njihove živote i pričajući njihove krio svoj. Neispričane priče ostajale su u režijskoj bilježnici kao u nekoj dobro začepljenoj boci. I odjednom, vjerojatno u nadi da ću time olakšati povratak, odlučio sam tu bocu otvoriti.“ Ovako Rajko Grlić, proslavljeni hrvatski reditelj svetskog glasa, u uvodu svojih Neispričanih priča objašnjava motive za nastanak ove knjige. U formi leksikona filmskih termina autor je u ovoj izuzetnoj ličnoj povesti izneo svoj pogled ne samo na svoju porodicu i svoju karijeru, nego i na zajedničku nekadašnju zemlju, prijatelje, kolege i događaje na jugoslovenskim prostorima u prelomnim vremenima za poslednjih pedesetak godina. Svaki filmski termin, pritom, sadrži kratku definiciju i značenje date filmske pojave, a onda Grlić u tom tematskom ključu, na veoma duhovit, dirljiv, a ponekad i gorak način, priča neku od epizoda ili iz svog života ili iz scenarija nekog od svojih nerealizovanih filmova. Od porodičnih nevolja i strahota tokom i posle Drugog svetskog rata, preko studiranja u praškoj školi filmskih umetnosti u vreme dramatičnih događaja sovjetske okupacije Čehoslovačke 1968, do najnovijih, postjugoslovenskih vremena kada se preselio u SAD i nastavio filmsku karijeru na relaciji Zagreb – Athens (Ohajo), Grlić sa nesumnjivim darom i za književni izraz ispreda uzbudljive priče koja će pogoditi svakoga ljubitelja dobre priče i poklonika iskrene i nepatvorene lične ispovesti o zajedničkoj nedavnoj prošlosti."},
    {"id": "26", "naziv": "Knjiga od peska", "pisac": "Horhe Luis Borhes", "zanr": "Avanturistički", "slika": "img/knjigaOdPeska.jpg", 
    "opis": "„Ekonomičnost proze, suptilnost imaginacije, hrabrost misli. Zbog toga mu se divimo.“ Džon Apdajk Februara 1969. u Kembridžu, na obali reke Čarls, sada već potpuno slep Borhes sreće čoveka čiji mu se glas učini zastrašujuće poznato. Ispostavlja se da je to dvadesetogodišnji Borhes, koji u Ženevi sedi na obali reke Rone… Knjiga od peska, poslednja Borhesova zbirka, sadrži trinaest nezaboravnih kratkih priča. To su fantastične pripovesti, snoviđenja, čak susreti sa sablasnim prikazama: sa svojim dvojnikom; sa Ulrikom, vitkom i svetlom, dalekim odjekom nordijske sage; sa starcem, bledim i ozbiljnim, koji dolazi iz budućnosti gde se uči umeće zaboravljanja. To su i susreti sa predmetima iz košmara, kao što je dijabolična knjiga od peska, koja nema ni početka ni kraja, ni središta ni reda, te svojom beskonačnošću remeti poredak stvarnosti."},
    {"id": "27", "naziv": "Forenzika Itake", "pisac": "Vule Žurić", "zanr": "Avanturistički", "slika": "img/forenzika.jpg", 
    "opis": "Najbolje i nove priče. Ovaj presek najboljih priča jednog od najznačajnijih savremenih srpskih pisaca obuhvata izbor iz njegovih zbirki Umri muški, Dvije godine hladnoće, U krevetu sa Madonom, Valceri i snošaji, Katenačo i Tajna crvenog zamka. Književni sladokusci konačno su u prilici da na jednom mestu uživaju u parodičnim, duhovitim, ali često i gorkim slikama vremena u predvečerje i u jeku raspadanja zemlje koja i dan danas, uprkos tolikim naporima, tvrdoglavo odbija da umre. Žurićeve književne likove ispunjava ceo jedan repertoar velikih iluzija koje se gube u njihovim sudbinama čiji je nepovoljan ishod ponajčešće nametnut tuđom voljom. Zbirku Žurićevih pripovedačkih standarda zatvara pet novih priča."},
    {"id": "28", "naziv": "Atlas opisan nebom", "pisac": "Goran Petrović", "zanr": "Avanturistički", "slika": "img/atlas.jpg", 
    "opis": "„Vi koji ulazite među ove stranice zaboravite sve što znate.“ Transfuge „Čitalac poznaje svakodnevne činjenice koje mu daju na uvid novine i televizija, a Petrović ga poziva da otkrije svet koji je ispod površine tih činjenica: svet snova i intuicija na kojima se one zasnivaju. Njegov Atlas ne svedoči o istorijskoj sadašnjosti, nego o sveukupnoj istoriji, ne o sitnodušnoj želji za osvajanjem i za ličnom vlašću koju svi trpimo dan za danom, nego o jednoj mnogo većoj ambiciji: osvajanju sveukupnog prostora i sveukupnog vremena. Možda upravo zato i sanjamo, zamišljamo budućnost, možda zato čitamo raskošne fikcije kao je što je ovaj Atlas opisan nebom.“ Alberto Mangel  (iz predgovora španskom i francuskom izdanju)"},
    {"id": "29", "naziv": "Sve u svemu", "pisac": "Ivana Dimić", "zanr": "Avanturistički", "slika": "img/sveUSvemu.jpg", 
    "opis": "Dobitnica Ninove nagrade. Fragment, zapis, minijatura – omiljene su forme kratke priče Ivane Dimić, pri čemu je svaka otvorena za tumačenje, provokativna a istovremeno melanholična, duhovita i otporna na svrstavanje u savremene književne tokove. Bilo da piše o češlju, tkaču vetrova, oblacima ili kandidatima za muža, o Gogolju, Kavafiju ili Crnjanskom, Ivana Dimić uvek nas iznenađuje nečim što prepoznajemo u svakodnevnom životu, pretačući u proznu formu univerzalne i suštinske sadržaje. „Priče Ivane Dimić su kao malo ostrvo u moru današnjeg pripovedanja na srpskom jeziku. Neuporedive sa bilo čime što je na sceni, slobodne od svih stvarnih ili lažnih imperativa, izvan književne trke koja ionako ne vodi nikuda, i nikada se ne završava. Duboko su lične, neslične bilo čemu što mi pada na pamet, svaka rečenica u njima zaslužena je životom, i sa razlogom je napisana. Sada znam: reč je o čistim esencijalizmima, o trenucima proniknuća u sve što nas čini onim što jesmo.“ Mihajlo Pantić"},
    {"id": "30", "naziv": "Netipičan tip", "pisac": "Tom Henks", "zanr": "Avanturistički", "slika": "img/netipicanTip.jpg", 
    "opis": "Ova zbirka od sedamnaest izvanrednih priča dokazuje da je dvostruki oskarovac Tom Henks talentovan i kao pisac. Istočnoevropski emigrant blage naravi stiže u Njujork pošto ga je građanski rat u njegovoj zemlji lišio žene i razorio mu život. Čovek koji voli kuglanje odigra savršenu partiju, pa još jednu i još jednu, sve dok ne postane slavan u kuglaškom svetu i mora da odluči hoće li mu savršenstvo i slava upropastiti sve ono što zaista voli. Ekscentrični milijarder i njegova odana desna ruka otiskuju se na putovanje u unutrašnjost Amerike i otkrivaju motel koji je ostao bez gostiju, ljubav i poneku mrvicu stvarnog života. Ovo su samo neke od priča u prvoj zbirci Toma Henksa, pametne, neočekivane, tople i, za milione onih koji vole Henksa, štivo koje se neizostavno mora pročitati. „Netipičan tip pruža toplu ljupkost i nostalgiju za nekim nežnijim i jednostavnijim vremenima – svejedno što ni ona možda nikad nisu bila ni toliko nežna ni toliko jednostavna.“ NPR"},
    {"id": "31", "naziv": "Alef", "pisac": "Horhe Luis Borhes", "zanr": "Avanturistički", "slika": "img/alef.jpg", 
    "opis": "Videh Alef, sa svih strana, videh u Alefu Zemlju, i u Zemlji opet Alef i u Alefu Zemlju... Dvojica hrišćanskih teologa vode žučnu raspravu o Svetom pismu. Vojnik tek na bojnom polju shvata ko je on zapravo. Mlada žena priprema perfidnu osvetu navodnom ubici svog oca. Muškarac u jednoj gostionici u Buenos Ajresu čeka na svog ubicu. Nacista se – bez trunčice griže savesti i nagoveštaja pokajanja – priseća vremena kada je bio čuvar u koncentracionom logoru. Iako su priče u Alefu ispunjene filozofskim zagonetkama i gotovo natprirodnim neobičnostima, one nam dočaravaju izgrađenije ljudske karaktere, možda i više nego ostale Borhesove pripovedačke knjige. Čak se ni pitanja besmrtnosti, večnosti, vremena i beskonačnosti ne gube u čistoj apstrakciji, već zadiru u zaplet i sintaksu ispitujući granice jezika i izrecivosti."},
    {"id": "32", "naziv": "Iznenada neko pokuca na vrata", "pisac": "Etgar Keret", "zanr": "Avanturistički", "slika": "img/iznenada.jpg", 
    "opis": "Genije kratke priče. Ako mene pitate, ono što se dogodilo Avišaju Abudiju treba da bude upozorenje za sve nas. Teško da ste mogli naći prosečnijeg i bezličnijeg čoveka od njega. On nije neko ko bi šutirao i prevrtao kontejnere ili započinjao tuču u pabu. Zapravo, nikad nije uradio ništa što bi privuklo nečiju pažnju. A ipak, jednog dana, iz čista mira, na vrata mu zalupaše dvojica siledžija. Odvukli su ga niz stepenice, ubacili u zadnji deo nekog kombija i odvezli pravo kod njegovih roditelja. I sve to dok prestravljeni Avišaj otpozadi viče: „Ko ste vi? Šta želite?“ „To nije ono što treba da se pitaš“, kaže vozač, a silos pored njega klima glavom. „Treba da se pitaš ’Ko sam ja?’ i ’Šta ja želim?’“ Etgar Keret je jedan od majstora savremene kratke proze. Paradoksalan poput Kafke, ironičan poput Vonegata, komedijaš poput Vudija Alena, a ipak autentičan, urnebesan, pronicljiv i uvek neobičan."},
    {"id": "33", "naziv": "Tamo je ovde", "pisac": "Maja Lalević Piščević", "zanr": "Avanturistički", "slika": "img/tamoJeOvde.jpg", 
    "opis": "Morala je da ode u Njujork, da bi se vratila sebi. Znala je to. Ali nije znala šta je tamo čeka. „Godinama smo u Nedeljniku tragali za kolumnistkinjom. Ali, već u prvom tekstu Maje Piščević usledilo je iznenađenje. Odmah je uspela ono što mnogima ne uspe za ceo život – da gane čitaoce. Nismo dobili kolumnu, već pisca. Brzo sam shvatio da smo svedoci romana u nastajanju. Ženski Kapor u Njujorku! I to 2016. Može li bolje?“ Veljko Lalić, glavni urednik Nedeljnika „U mladosti, Njujork nam je uvek bio neki metafizički Beograd u kojem se događala naša paralelna stvarnost. Sve njujorške priče, parkovi, kvartovi ili umetnici bili su neizreciv deo naših ljubavi, pesama i priča. Nije bilo potrebno živeti tamo, Njujork je bio literarni obrazac u nama. Onda je prošla ta mladost i zamenila ju je stvarnost, u kojoj je Njujork postao grad u koji se Maja odselila. I u kojem je napisala jedan divan, ličan i tajanstven dnevnik preobražaja. Pišući o Njujorku, Maja piše, meni se čini, o Beogradu koji više ne postoji.“ Srđan Šaper"},
    {"id": "34", "naziv": "Deseti decembar", "pisac": "Džordž Sonders", "zanr": "Avanturistički", "slika": "img/desetiDecembar.jpg", 
    "opis": "Dobitnik Bukerove nagrade. „Priče u zbirci Deseti decembar Džordža Sondersa počinju kao eksperimenti, naizgled složene igre jezikom i formom, ali se sa svakim redom otkrivaju čitaocu, pojednostavljuju do granica parabole. Na početku ste suočeni s isprepletanim glasovima pripovedača, sa „zamršenom mozgalicom“, dok na kraju ne ostanete pred jednostavnim izborom. Dobro ili zlo. Život ili smrt. Knjiga Deseti decembar jedna je od najvažnijih zbirki pripovedaka objavljenih u poslednjoj deceniji. Piscu je donela književnu slavu, baš kao i prvi roman Linkoln u Bardu, nagrađen Bukerovom nagradom 2017. godine.“ Iz pоgovora Miće Vujičića „Zaprepašćujuće naštimovano pero – graciozno, mračno, samosvojno i duhovito – koje ispisuje upravo priče kakve su nam neophodne u ovakvim vremenima.“ Tomas Pinčon"},
    {"id": "35", "naziv": "Preživljavanje", "pisac": "Dragoslav Mihailović", "zanr": "Avanturistički", "slika": "img/prezivljavanje.jpg", 
    "opis": "Vitalova nagrada za knjigu godine. „Sedam priča Mihailovićeve knjige Preživljavanje tematizuje svet rata i poratnog vremena – kraja prve polovine dvadesetog veka, u kojem pisac traga za mogućnostima da ispriča neispričivo, ono što je za mnoge svedoke u ratnim i poratnim godinama evropske istorije bilo neizrecivo kao granično iskustvo zla.“ Jovan Zivlak „Ove pripovetke nisu prosto slike iz prošlosti, već slike iz budućnosti. Jer čitaoci ne idu za tim da u delu prepoznaju samo ono što je viđeno, nego da još više slute u njemu ono neviđeno.“ Nikola Strajnić"},
    {"id": "36", "naziv": "Unutrašnje dvorište", "pisac": "Goran Petrović", "zanr": "Avanturistički", "slika": "img/unutrasnje.jpg", 
    "opis": "Nagrade „Ivo Andrić“, „Borisav Stanković“, „Svetozar Ćorović“, „Prosvetina“ i nagrada „Veljkova golubica“ za sveukupno pripovedačko delo. Kao što je prvom svojom knjigom Saveti za lakši život utro put poetičkim rukavcima u svojim kasnijim pripovetkama i romanima, tako je pričama iz ove knjige Goran Petrović uverljivo omeđio svoj razuđeni pripovedački prostor. Njegovi književni junaci oblikuju jedan čudesan, sanjani svet – suset iz zgrade pretvara se u anđela, grupa prijatelja koja tajno ulazi u jedan pejzaž akvarela, likovi koji skidaju kolutove dima sa zidova i nameštaja, koračaju lebdeći iznad zemlje, bojadišu Feniksov pepeo, daju lekcije uvažavanja ili se bave iskopavanjem sreće... Svi oni teže da izađu iz bezlične svakodnevice, zakorače u predeo mašte i tako ožive jedinstven književni mikrokosmos kojim se nadograđuju ustaljeni prozni postupci u srpskoj književnosti na prelazu dva veka."}
    
];


    const idKartice = document.querySelector("#kartice");

    function prikaz(){
        for(let k of knjige){
            idKartice.innerHTML += `
                <div data-aos="fade-up" id="card" class="col-lg-2 col-md-4 col-sm-6">
                    <img id="slikaK" src="${k.slika}">
                    <p id="nameCard">${k.naziv}</p>
                    <p id="writeCard">${k.pisac}</p>
                </div>
            ` 
        }
    } prikaz()

    
    const idSlikaKnjige = document.querySelector("#slikaKnjige");
    const idOpisKnjige = document.querySelector("#opisKnjige");
    
    idKartice.addEventListener('click', function(){
        for(let k of knjige){
            if(k = k.id){
                idSlikaKnjige.innerHTML += `
                    <img id="slikaK" src="${k.slika}">
                `;
            }
        }
    });